### PR TITLE
Fix for PyInit_PyHSPlasma visibility on Py <3.9

### LINKED ISSUE #248: CMake visibility changes break PyHSPlasma on Python < 3.9
Essentially, `PyInit_PyHSPlasma` isn't marked as visible, so the module initialization fails.

This is fixed in Python >= 3.9 because they added visibility attributes to the `PyMODINIT_FUNC` macro, however some of us are still building with Python 3.7 to run korman on Linux with Blender 2.79 (which depends on Python 3.7).

Based on how libHSPlasma and libHSPlasmaNet are doing things, I imagine there's some sort of `PYHSPLASMA_EXPORT` thing that could be added here to make it visible, but I don't know enough about where and how CMake is defining these macros to be sure of that...

### PR DESCRIPTION
**Pull request by dpogue**
libHSPlasma has been configured to use proper symbol visibility, which has resulted in all of the PyHSPlasma symbols being marked hidden.
`PyMODINIT_FUNC` on Python 3.9+ has been updated to include visibility annotations, but on earlier versions it is missing.

I've confirmed this is working for me when building for Python 3.7.

Closes #248

### CODE REVIEW

File: Python/Module.cpp [hunk 1]
```diff
@@ -455,6 +455,15 @@ static void initPyHSPlasma_Constants(PyObject* module)
     PyModule_AddIntConstant(module, "KEY_UNMAPPED", KEY_UNMAPPED);
 }
 
+#if ((PY_MAJOR_VERSION == 3) && (PY_MINOR_VERSION < 9)) && defined(__GNUC__)
+#   define BEGIN_EXPORTED_DECLARATION _Pragma("GCC visibility push(default)")
+#   define END_EXPORTED_DECLARATION _Pragma("GCC visibility pop")
```
Comment (zrax) [inline Python/Module.cpp:460]: Why not use an attribute (`__attribute__((visibility("default")))`) instead of needing to wrap the whole function body in begin/end macros?  The attribute macro can be placed after `PyMODINIT_FUNC` to ensure it takes priority over whatever `PyMODINIT_FUNC` defines...

Comment (dpogue) [reply Python/Module.cpp:460]: I tried that and it said the attribute was in the wrong spot and would be ignored.

`PyMODINIT_FUNC` is `extern "C" PyObject*`, and I think it wants the attribute before the `PyObject*` return type

Comment (zrax) [reply Python/Module.cpp:460]: Ah, yeah, that does make it more annoying...  However, you could also forward-declare it with the attribute at the end:

```c++
PyMODINIT_FUNC PyInit_PyHSPlasma() __attribute__((visibility("default")));

PyMODINIT_FUNC PyInit_PyHSPlasma()
{
    ...
}
```

Comment (dpogue) [reply Python/Module.cpp:460]: Ahh okay, that's much cleaner.

Comment (dpogue) [reply Python/Module.cpp]: I'm not sure how "safe" it is to reuse `HSPLASMA_EXPORT` outside of the libHSPlasma core module itself, but it seems to work.

Comment (zrax) [reply Python/Module.cpp]: I'm more worried about how "safe" it is to use in a location not documented as supported by CMake, since that macro now comes from CMake's GenerateExportHeader module.

Comment (dpogue) [reply Python/Module.cpp]: This seems like it would be safe to have unconditionally?

```cpp
PyMODINIT_FUNC PyInit_PyHSPlasma() [[gnu::visibility("default")]];
```

Python 3.7 already (as far as I can tell) annotates it with `__declspec(dllexport)` for MSVC

Comment (dpogue) [reply Python/Module.cpp]: Apparently `__attribute__((visibility("default")))` is the only thing that works... `[[gnu::visibility("default")]]` is ignored on non-class types 🙄

**Review by zrax — APPROVED** [review]
